version: 2

sources:
  - name: crosschain
    database: "{{ 'crosschain' if target.database == 'aleo' else 'crosschain_dev' }}"
    schema: core
    tables:
      - name: dim_labels

  - name: crosschain_silver
    database: "{{ 'crosschain' if target.database == 'ALEO' else 'crosschain_dev' }}"
    schema: silver
    tables:
      - name: number_sequence
      - name: labels_combined
      - name: complete_token_asset_metadata
      - name: complete_token_prices
      - name: complete_provider_asset_metadata
      - name: complete_provider_prices
      - name: complete_native_asset_metadata
      - name: complete_native_prices

  - name: bronze_streamline
    database: streamline
    schema: |
      "{{ 'ALEO' if target.database == 'ALEO' else 'ALEO_DEV' }}"
    tables:
      - name: blocks
      - name: transactions
      
  - name: github_actions
    database: ALEO
    schema: github_actions
    tables:
      - name: workflows